# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

wt1 = Top.create(image_url: , brand: Nike, style: )
wt2 = Top.create(image_url: , brand: Nike, style: )
wt3 = Top.create(image_url: , brand: Nike, style: )
wt4 = Top.create(image_url: , brand: Nike, style: )
wt5 = Top.create(image_url: , brand: Nike, style: )
wt6 = Top.create(image_url: , brand: Nike, style: )
wt7 = Top.create(image_url: , brand: Nike, style: )
wt8 = Top.create(image_url: , brand: Nike, style: )
wt9 = Top.create(image_url: , brand: Nike, style: )
wt10 = Top.create(image_url: , brand: Nike, style: )

wt11 = Top.create(image_url: , brand: Club Monaco, style: )
wt12 = Top.create(image_url: , brand: Club Monaco, style: )
wt13 = Top.create(image_url: , brand: Club Monaco, style: )
wt14 = Top.create(image_url: , brand: Club Monaco, style: )
wt15 = Top.create(image_url: , brand: Club Monaco, style: )
wt16 = Top.create(image_url: , brand: Club Monaco, style: )
wt17 = Top.create(image_url: , brand: Club Monaco, style: )
wt18 = Top.create(image_url: , brand: Club Monaco, style: )
wt19 = Top.create(image_url: , brand: Club Monaco, style: )
wt20 = Top.create(image_url: , brand: Club Monaco, style: )

wt21 = Top.create(image_url: , brand: , style: )
wt22 = Top.create(image_url: , brand: , style: )
wt23 = Top.create(image_url: , brand: , style: )
wt24 = Top.create(image_url: , brand: , style: )
wt25 = Top.create(image_url: , brand: , style: )
wt26 = Top.create(image_url: , brand: , style: )
wt27 = Top.create(image_url: , brand: , style: )
wt28 = Top.create(image_url: , brand: , style: )
wt29 = Top.create(image_url: , brand: , style: )
wt30 = Top.create(image_url: , brand: , style: )

wt31 = Top.create(image_url: , brand: , style: )
wt32 = Top.create(image_url: , brand: , style: )
wt33 = Top.create(image_url: , brand: , style: )
wt34 = Top.create(image_url: , brand: , style: )
wt35 = Top.create(image_url: , brand: , style: )
wt36 = Top.create(image_url: , brand: , style: )
wt37 = Top.create(image_url: , brand: , style: )
wt38 = Top.create(image_url: , brand: , style: )
wt39 = Top.create(image_url: , brand: , style: )
wt40 = Top.create(image_url: , brand: , style: )

wt41 = Top.create(image_url: , brand: , style: )
wt42 = Top.create(image_url: , brand: , style: )
wt43 = Top.create(image_url: , brand: , style: )
wt44 = Top.create(image_url: , brand: , style: )
wt45 = Top.create(image_url: , brand: , style: )
wt46 = Top.create(image_url: , brand: , style: )
wt47 = Top.create(image_url: , brand: , style: )
wt48 = Top.create(image_url: , brand: , style: )
wt49 = Top.create(image_url: , brand: , style: )
wt50 = Top.create(image_url: , brand: , style: )